2022-03-24 16:27:21,448 INFO    MainThread:174410 [wandb_setup.py:_flush():75] Loading settings from /home/ludvik/.config/wandb/settings
2022-03-24 16:27:21,449 INFO    MainThread:174410 [wandb_setup.py:_flush():75] Loading settings from /home/ludvik/Desktop/rs_sb3/wandb/settings
2022-03-24 16:27:21,449 INFO    MainThread:174410 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-24 16:27:21,449 INFO    MainThread:174410 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-24 16:27:21,449 INFO    MainThread:174410 [wandb_init.py:_log_setup():405] Logging user logs to /home/ludvik/Desktop/rs_sb3/wandb/run-20220324_162721-2zcqt0w2/logs/debug.log
2022-03-24 16:27:21,449 INFO    MainThread:174410 [wandb_init.py:_log_setup():406] Logging internal logs to /home/ludvik/Desktop/rs_sb3/wandb/run-20220324_162721-2zcqt0w2/logs/debug-internal.log
2022-03-24 16:27:21,449 INFO    MainThread:174410 [wandb_init.py:init():439] calling init triggers
2022-03-24 16:27:21,449 INFO    MainThread:174410 [wandb_init.py:init():442] wandb.init called with sweep_config: {}
config: {}
2022-03-24 16:27:21,449 INFO    MainThread:174410 [wandb_init.py:init():492] starting backend
2022-03-24 16:27:21,449 INFO    MainThread:174410 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-24 16:27:21,453 INFO    MainThread:174410 [backend.py:ensure_launched():219] starting backend process...
2022-03-24 16:27:21,459 ERROR   MainThread:174410 [wandb_init.py:init():981] error
Traceback (most recent call last):
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 954, in init
    run = wi.init()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 499, in init
    backend.ensure_launched()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 222, in ensure_launched
    self.wandb_process.start()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
