Process ForkServerProcess-3:
Traceback (most recent call last):
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 24, in _worker
    env = env_fn_wrapper.var()
  File "/home/ludvik/Desktop/rs_sb3/local_multi.py", line 72, in _init
    env = makeEnv(cfg)
  File "/home/ludvik/Desktop/rs_sb3/local_multi.py", line 26, in makeEnv
    env = suite.make(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 39, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 193, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/manipulation/manipulation_env.py", line 162, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/robot_env.py", line 213, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 138, in __init__
    self._initialize_sim()
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 245, in _initialize_sim
    self.initialize_time(self.control_freq)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 188, in initialize_time
    if control_freq <= 0:
TypeError: '<=' not supported between instances of 'tuple' and 'int'
Process ForkServerProcess-4:
Traceback (most recent call last):
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 24, in _worker
    env = env_fn_wrapper.var()
  File "/home/ludvik/Desktop/rs_sb3/local_multi.py", line 72, in _init
    env = makeEnv(cfg)
  File "/home/ludvik/Desktop/rs_sb3/local_multi.py", line 26, in makeEnv
    env = suite.make(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 39, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 193, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/manipulation/manipulation_env.py", line 162, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/robot_env.py", line 213, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 138, in __init__
    self._initialize_sim()
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 245, in _initialize_sim
    self.initialize_time(self.control_freq)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 188, in initialize_time
    if control_freq <= 0:
TypeError: '<=' not supported between instances of 'tuple' and 'int'
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 24, in _worker
    env = env_fn_wrapper.var()
  File "/home/ludvik/Desktop/rs_sb3/local_multi.py", line 72, in _init
    env = makeEnv(cfg)
  File "/home/ludvik/Desktop/rs_sb3/local_multi.py", line 26, in makeEnv
    env = suite.make(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 39, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
  File "/home/ludvik/Desktop/rs_sb3/custom_task.py", line 193, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/manipulation/manipulation_env.py", line 162, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/robot_env.py", line 213, in __init__
    super().__init__(
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 138, in __init__
    self._initialize_sim()
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 245, in _initialize_sim
    self.initialize_time(self.control_freq)
  File "/home/ludvik/.local/lib/python3.8/site-packages/robosuite/environments/base.py", line 188, in initialize_time
    if control_freq <= 0:
TypeError: '<=' not supported between instances of 'tuple' and 'int'
Traceback (most recent call last):
  File "run_multiple_tests.py", line 6, in <module>
    run_training(cfg)
  File "/home/ludvik/Desktop/rs_sb3/local_multi.py", line 85, in run_training
    vec_gym_env = SubprocVecEnv([make_env(i , cfg) for i in range(num_cpu)])
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 111, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/ludvik/anaconda3/envs/RS_SB3_test/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer